spring:
  application:
    name: xmtx-provider-redis
  redis:
    host: 127.0.0.1
    password: 123456



eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 3000
