spring:
  application:
    name: xmtx-provider-jobfair
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/db_mj4x?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/dbxmtx?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  redis:
    host: 127.0.0.1
    password: 123456
  cache:
    redis:
      use-key-prefix: true
      key-prefix: jobCache
      cache-null-values: false
      time-to-live: 12h
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
server:
  port: 8083
