server:
  port: 2002

# spring配置
spring:
  application:
    name: xmtx-provider-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_mj4x?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/dbxmtx?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

# eureka配置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
